FROM python:3.10-slim

ADD ./requirements /requirements
RUN python3 -m pip install --upgrade pip && python3 -m pip install -r ./requirements/base.txt

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

ADD  ./app /app/app