version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "5430:5432"
    volumes:
      - ./local/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Maks
      - POSTGRES_PASSWORD=Maks
      - POSTGRES_DB=lazycook

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5480:80"

  web:
    build:
      context: .
      dockerfile: ./dockerfile.yml
    env_file:
      - .env.local
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - PYTHONPATH=/app
    command: bash -c "cd /app/app/alembic && alembic upgrade head && cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app/app
    ports:
      - "7000:8000"
    depends_on:
      - db